name: Append to README
# Triggers after every push 
on:
  push:
    branches:
      - main
jobs:
  append-text:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Append text to README.md
      run: echo "An edit was made, this message was written dynamically!" >> README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Appended new text to README.md"
        git push
